name: Continuous Integration

on:
  push:
    branches: master
  pull_request:
    branches: master

defaults:
  run:
    shell: pwsh

jobs:
  manifest_check:
    name: Validate Manifest
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate package manifests
      run: .github/workflows/check-manifests
  syntax_check:
    name: Validate Syntax
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download LuaJIT binaries
      with:
        repository: luapower/luajit
        path: .tools
      uses: actions/checkout@v2
    - name: Validate Lua syntax
      run: .github/workflows/check-syntax
  version_check:
    name: Check Version
    runs-on: windows-2019
    if: github.event_name == 'pull_request'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Check version numbers
      run: .github/workflows/check-versions
